# Generated by Django 3.2.8 on 2021-12-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('body', models.CharField(max_length=1024)),
            ],
        ),
    ]
